- name: ACI Setup
  hosts: localhost
  connection: local
  gather_facts: false
 
  vars_files:
   - variable.yaml
  
  tasks:

  - name: Create XML posts from templates
    template: src={{ item.src }} dest={{ item.dest }}
    with_items:
      - { src: '../delete_posts/delete_ldev.j2',                   dest: '../delete_posts/delete_ldev.xml' }
      - { src: '../delete_posts/delete_contract.j2',               dest: '../delete_posts/delete_contract.xml' }
      - { src: '../delete_posts/delete_service_graph_template.j2', dest: '../delete_posts/delete_service_graph_template.xml'}
      - { src: '../delete_posts/delete_deviceSelectionPolicy.j2',  dest: '../delete_posts/delete_deviceSelectionPolicy.xml'}
      - { src: '../delete_posts/detach_contract.j2',               dest: '../delete_posts/detach_contract.xml'}
  
  - name: Execute DELETE (Contract, Apply Contract to EPG, Create LDEV, Service Graph Template, Device selection policy , Apply graph)
    aci_rest:
      action: "post"
      path: "/api/node/mo/uni/tn-{{tenant_name}}.xml"
      config_file: "{{ item }}"
      host: "{{apic_ip}}"
      username: "{{apic_username}}"
      password: "{{apic_password}}"
      validate_certs: "false"
    with_items:
     - "../delete_posts/delete_contract.xml"
     - "../delete_posts/detach_contract.xml"
     - "../delete_posts/delete_deviceSelectionPolicy.xml"
     - "../delete_posts/delete_service_graph_template.xml"
     - "../delete_posts/delete_ldev.xml"
