- name: ACI 
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
   vlan_encap: []

  vars_files:
    - aci_unmanaged_vars_combined_ldev.yml

  tasks:

  - name: Get VLAN information from a deployed graph 
    aci_rest:
      action: "get"
      uri: "/api/node/mo/uni/tn-{{tenant_name}}/GraphInst_C-[uni/tn-{{tenant_name}}/brc-{{contract_name}}]-G-[uni/tn-{{tenant_name}}/AbsGraph-{{SGtemplate_name}}]-S-[uni/tn-common/ctx-default]/NodeInst-N1.json?query-target=subtree&target-subtree-class=vnsEPgDef"
      host: 10.192.73.50
      username: admin
      password: cisco123
      validate_certs: "false"
    register: vlans

  - name: debug
    debug: msg="{{vlans}}"

  - set_fact:
      vlan_encap: "{{ vlan_encap|default([]) + [ {'name': item.name, 'encap': item.encap.split('-')[1] }] }}"
    loop: "{{vlans | json_query(query_string)}}"
    vars:
     query_string: "imdata[*].vnsEPgDef.attributes"

  - debug: "msg={{vlan_encap}}"
